import React from "react";

const TermsandConditon = () => {
  document.title = 'Terms & Conditions'
  return (
    <div>

      {" "}
      <div className="privacywrapper mb-4">
        <h1 className="privacyhead text-4xl">Terms & Conditions</h1>
        <div className="privacyMain">
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            This document is published in accordance with the provisions of Rule 3(1) of Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of through the domain and sub-domains of Beiyo located at www.beiyo.in and/or through “Beiyo – Student or Working Professional Residence Community” mobile applications (collectively referred to herein as the "Platform").
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            The Platform is owned by BEIYO TECHNVEN PRIVATE LIMITED , a company incorporated under the Companies Act, 1956 with its registered office at Flat No. 1107 Topaz B Type, Rainbow Residency, Vallabhnagar Indore, Madhya Pradesh, 452003 India (hereinafter referred to as "Platform Owner", "we", "us", "our").
          </p>
          <p style={{ marginBottom: "1rem" }}>
          This Terms of Use agreement was last updated on 30 November, 2024.
          </p>
          <p style={{ marginBottom: "1rem" }}>
          This Terms of Use agreement is effective as of 02 April, 2024.
          </p>
          <h1 className="font-bold">Definations:</h1>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            <span className="font-bold">“Data”</span> means a representation of information, knowledge, facts, concepts, or instructions which are being prepared or have been prepared in a formalized manner, and is intended to be processed, is being processed, or has been processed in a computer system or computer network, and may be in any form (including computer printouts, magnetic or optical storage media, punched cards, punched tapes) or stored internally in the memory of the computer.
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            <span className="font-bold">“Information”</span>  includes data, messages, text, images, sound, voice, codes, computer programs, software, and databases or microfilm or computer-generated microfiche.
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            <span className="font-bold">"Password"</span>  means a secret word, phrase, code, passphrase, or secret key, or encryption or decryption keys used to gain admittance or access to information.
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            <span className="font-bold">"Personal information"</span> means any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with a body corporate, is capable of identifying such a person.
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            <span className="font-bold">"Services"</span> shall mean residence, accommodation, including but not limited to housekeeping services, food services, and other services while staying at Beiyo hostels.
          </p>
          <p style={{ marginBottom: "1rem" }}>
            {" "}
            <span className="font-bold">"Sensitive personal data or information"</span> Sensitive personal data or information of a person means such personal information which consists of information relating to:
          </p>
          <ol className="mt-4 mb-4">
          <li>Password</li>
          <li>Financial information such as bank account or credit card or debit card or other payment instrument details</li>
          <li>Physical, physiological, and mental health condition</li>
          <li>Sexual orientation</li>
          <li>Medical records and history</li>
          <li>Biometric information</li>
          </ol>

          <hr />

          <h1 className="font-bold">A. ACCEPTANCE OF TERMS</h1>
          <p style={{ marginBottom: "1rem" }}>
          PLEASE READ THE TERMS OF USE THOROUGHLY AND CAREFULLY.
          </p>
          <p style={{ marginBottom: "1rem" }}>
          All references to "you" or "your" or “user” as applicable, mean the person that accesses, uses, and/or participates in the Platform in any manner. “You” or “your” or “user” would include the parent and/or guardian of such a minor. In the event any person who accesses, uses, and/or participates in the Platform is a minor (i.e., less than 18 years of age), then such an individual shall be obligated to cause and procure the minor to adhere to the obligations as set out hereunder.
          </p>
          <p style={{ marginBottom: "1rem" }}>
          The terms and conditions set forth below ("Terms of Use") and the Privacy Policy (as defined below) constitute a legally binding agreement between Beiyo and you. These Terms of Use contain provisions that define your limits, legal rights, and obligations with respect to your use of and participation in the Beiyo Platform, including the classified advertisements, forums, various email functions, and Internet links, and all content and Beiyo services available through the Platform.
          </p>
          <p>Currently, the services pertain to five broad sections, which are:</p>
          <ul className="mt-4 mb-4">
            <li>Feedback</li>
            <li>Check-Ins</li>
            <li>Complaint Management</li>
            <li>Beiyo Social</li>
            <li>Beiyo Mates</li>
          </ul>
          <p className="mb-4">(such services collectively referred to as the "Services"). Beiyo reserves the right to add or remove any services at any time on such terms as it deems fit. The Terms of Use described below incorporate the Privacy Policy and apply to all users of the Platform</p>
         <p className="mb-4">You acknowledge that the Platform serves as a venue for the online distribution and publication of user-submitted information between various users. By using, visiting, registering for, and/or otherwise participating in this Platform, including the Services presented, promoted, and displayed on the Platform, and by clicking on "I have read and agree to the terms of use,” you hereby certify that:</p>
         <ul className="mt-4 mb-4">
            <li>You are duly registered with Beiyo in case you are using the App</li>
            <li>You have the authority to enter into these Terms of Use</li>
            <li>You agree to be bound by all terms and conditions of these Terms of Use and any other documents incorporated by reference herein</li>
            <li>Beiyo Social</li>
            <li>Beiyo Mates</li>
          </ul>
          <p className='mb-4'>If you do not agree to any of the provisions set forth in the Terms of Use, kindly discontinue viewing or participating in this Platform immediately.
          </p>
         <p className="mb-4">YOU SPECIFICALLY AGREE THAT BY USING THE PLATFORM, YOU ARE EITHER <br /> (i) AT LEAST 18 YEARS OF AGE AND OF SOUND MIND AND YOU ARE COMPETENT UNDER LAW TO ENTER INTO A LEGALLY BINDING AND ENFORCEABLE CONTRACT OR  (ii) ARE THE PARENT AND/OR GUARDIAN OF THE MINOR USING THE PLATFORM, AND YOU ARE COMPETENT UNDER LAW TO ENTER INTO A LEGALLY BINDING AND ENFORCEABLE CONTRACT ON BEHALF OF THE MINOR AND THE SAID MINOR SHALL BE BOUND BY THE SAME.</p>
        <hr />
        <h2 className="font-bold">1. Modifications to Terms of Use and/or Privacy Policy</h2>
        <p className="mb-4">Beiyo Technven Private Limited reserves the right, in its sole discretion, to change, modify, or otherwise amend the Terms of Use and any other documents incorporated by reference herein for complying with the legal and regulatory framework and for other legitimate business purposes, at any time, without notice. Beiyo will post the amended Terms of Use on the domain of http://beiyo.in/terms-and-conditions.</p>
        <p className="mb-4">It is your responsibility to review the Terms of Use for any changes, and you are encouraged to check the Terms of Use frequently. Your use of the Platform following any amendment of the Terms of Use will signify your assent to and acceptance of any revised Terms of Use. If you do not agree to abide by these or any future Terms of Use, please do not use or access the Platform.        </p>
        <hr />
        <h2 className="font-bold">1. Modifications to Terms of Use and/or Privacy Policy</h2>
        <p className="mb-4">Beiyo has established a Privacy Policy that explains to users how their information is collected and used. The Privacy Policy is referenced above and hereby incorporated into the Terms of Use set forth herein.</p>
        <p className="mb-4">Your use of this Platform is governed by the Privacy Policy, which you may refer to for any grievances related to the collection, storage, and use of any Sensitive Personal Data and Personal Data as defined under the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011.
        </p>
        <p className="mb-4">The Privacy Policy is located at: http://beiyo.in/privacy-policy.
        </p>
        <hr />
        
        <h1 className="font-bold">B. MEMBERSHIP AND ACCESSIBILITY</h1>
        <h2 className="font-bold">1. License to Access</h2>
        <p className="mb-4">Beiyo hereby grants you a non-exclusive, revocable license to use the Platform as set forth in the Terms of Use; provided, however, that:
<br />(i) You will not copy, distribute, or make derivative works of the Platform in any medium without Beiyo's prior written consent;
<br />(ii) You will not alter or modify any part of the Platform other than as may be reasonably necessary to use the Platform for its intended purposes or if so requested by Beiyo; and
<br />(iii) You will otherwise act in accordance with the terms and conditions of the Terms of Use and in accordance with all applicable laws in India.
</p>
<h2 className="font-bold">2. Membership Eligibility Criteria</h2>
<p className="mb-4">
You represent, acknowledge, and agree that you are either (i) at least 18 years of age, or (ii) you, as a parent/guardian, agree to be bound as well as agree that your ward shall be bound, and you shall cause your ward to be bound by the present Terms of Use, and that:
<br />(a) All registration information that you submit is truthful and accurate;
<br />(b) You will maintain the accuracy of such information; and
<br />(c) Your use of the Platform and Services offered through this Platform does not violate any applicable law or regulation.
</p>

<p className="mb-4">Your account ("Account") may be terminated without warning if Beiyo, at its sole discretion, believes that you are violating the terms of this Terms of Use or are not complying with any applicable laws, rules, or regulations in India.</p>
<p className="mb-4">To access and participate in the Platform, you will need to create a password-protected account ("Account"). To create an account, you must submit your name, email address, and phone number through the account registration page on the Platform and create a password.
</p>
<p className="mb-4">You will also have the ability to provide additional/optional information, which is not required to register for an account but may be helpful to Beiyo in providing you with a more customized experience while using the Platform.</p>
<p className="mb-4">At the discretion of Beiyo, you may also be provided with the option of registering for an Account using your existing social network account and log-in credentials (your "Third-Party Site Password").</p>
<p className="mb-4">You are solely responsible for safeguarding your Beiyo password and, if applicable, your Third-Party Site Password (collectively, "Passwords") at all times. You shall be solely responsible for all activity that occurs on your Account and shall notify Beiyo immediately of any breach of security or unauthorized use of your Account. Similarly, you shall never use another member’s Account without Beiyo's permission.</p>
<p className="mb-4">You hereby expressly acknowledge and agree that you, and not Beiyo, will be liable for your losses, damages, etc. (whether direct or indirect) caused by unauthorized use of your Account. Notwithstanding the foregoing, you may be liable for the losses of Beiyo or others due to such unauthorized use. An Account holder is herein referred to as a "Registered User."</p>
<hr />

<h2 className="font-bold">3. Additional Policies</h2>
<p className="mb-4">Your access to, use of, and participation in the Platform is subject to the Terms of Use and all applicable Beiyo regulations, guidelines, and additional policies that Beiyo may set forth from time to time, including, without limitation, a copyright policy and any other restrictions or limitations that Beiyo publishes on the Platform ("Additional Policies").</p>
<p className="mb-4">You hereby agree to comply with the Additional Policies and your obligations thereunder at all times.</p>
<p className="mb-4">You acknowledge and agree that if you fail to adhere to any of the terms and conditions of this Agreement or documents referenced herein, including the Account Policies, membership eligibility criteria, or Additional Policies, Beiyo, in its sole discretion, may terminate your Account at any time without prior notice to you. Beiyo may also claim damages or initiate appropriate legal proceedings if necessary.</p>
    <hr />

    <h1 className="font-bold">MEMBER CONDUCT</h1>  
    <h2 className="font-bold">1. Prohibitions on Submitted Content</h2>
    <p className="mb-4">
    You shall not upload, post, transmit, transfer, disseminate, or distribute any content, including text, images, video, sound, data, or software to any part of the Platform, including your profile ("Profile") or the posting of any opinions or reviews in connection with the Platform or the Services ("Feedback"), that:
    </p>
    <p className="mb-4">(a) Misrepresents the source of anything you post, including impersonation of another individual or entity;
<br />(b) Invades privacy, violates copyrights, promotes illegal activity, or contains discriminatory content;
<br />(c) Contains viruses, spam, or advertising for pyramid schemes;
<br />(d) Is obscene, defamatory, or harassing;
<br />(e) Discriminates on the basis of race, religion, or other protected categories.</p>
<p className="mb-4">Beiyo reserves the right to remove any content that violates these conditions.</p>
<hr />
    <h2 className="font-bold">2. Prohibitions with Respect to Services</h2>
    <p className="mb-4">While using the Platform provided by Beiyo Technven Private Limited, you shall not:</p>
    <p className="mb-4">
   1. Post content or items in any inappropriate category or areas on the Platform.
<br />2. Violate any laws, third-party rights, Account policies, or any provision of the Terms of Use, including but not limited to the prohibitions described above.
<br />3. Fail to deliver payment for Services purchased by you.
<br />4. Circumvent or manipulate the fee structure, the billing process, or fees owed to Beiyo.
<br />5. Post false, inaccurate, misleading, defamatory, or libellous content, including personal information about any Platform user.
<br />6. Take any action that may undermine the Feedback or ratings systems (such as displaying, importing, or exporting Feedback information off the Platform or using it for purposes unrelated to the Platform).
    </p>
    <hr />
    <h2 className="font-bold">3. Feedback</h2>
   <h3 className="font-bold">A. Responsible Use of Feedback</h3>
   <p className="mb-4">As a participant on the Platform, you agree to exercise careful, prudent, and good judgment when providing Feedback to ensure its integrity and value for other users and the system.
   </p>
   <h3 className="font-bold">B. Sanctions for Inappropriate Feedback Use</h3>
   <p className="mb-4">If you violate any rules related to Feedback usage, <span className="font-bold">Beiyo Technven Private Limited</span>, at its sole discretion, may take any or all of the following actions:</p>
    <p className="mb-4">1. Cancel Feedback or Postings: Feedback or associated postings may be removed without notice.
<br />2. Account Restrictions: Account privileges may be limited based on the nature of the violation.
<br />3. Suspension of Account: Your account may be temporarily or permanently suspended for repeated or serious violations.
<br />4. Status Downgrades: Your account’s earned status through the Feedback system may be reduced or downgraded</p>
    <h3 className="font-bold">C. Reporting Inappropriate Feedback</h3>
    <p className="mb-4">If you encounter or suspect inappropriate Feedback use, you may report it to <span className="font-bold">Beiyo Technven Private Limited</span> by emailing support@beiyo.in. The report will be reviewed, and necessary action will be taken to uphold Platform integrity.</p>
    <h3 className="font-bold">D. Feedback Dispute Resolution</h3>
    <p className="mb-4">In cases of disputes related to Feedback between users of the Platform, Beiyo Technven Private Limited shall serve as the final and binding arbitrator. Furthermore, Beiyo Technven Private Limited, at its sole and absolute discretion, may take any action deemed appropriate, including:</p>
   <p className="mb-4">1. Removing disputed Feedback.
<br />2. Taking other reasonable actions without incurring any liability.
</p>
<p className="mb-4">It is important to note that Beiyo Technven Private Limited is not legally obligated to act in every dispute but will intervene where deemed necessary to maintain fairness and Platform standards.</p>
    <hr />
    <h2 className="font-bold">4. Prohibitions with Respect to the Platform</h2>
      <p className="mb-4">
      By agreeing to these Terms, you acknowledge and agree to comply with the following policies to ensure responsible use of the Platform:
      </p>
      <p className="mb-4">
     1. Unauthorized Copying or Distribution:
<br />You shall not copy, reproduce, or distribute any part of the Platform, its content, or associated materials without explicit prior written authorization from Beiyo Technven Private Limited.
<br />2. Accurate Information:
<br />When creating an account, you must provide true, accurate, current, and complete information. This information must be updated throughout your use of the Platform to remain accurate.
<br />3. Automated Systems:
<br />The use of automated systems or tools such as "robots," "scrapers," or "spiders" to access the Platform for any purpose is prohibited unless prior written approval is obtained from Beiyo Technven Private Limited.
<br />4. Data Misuse and Misappropriation:
<br />You must not, under any circumstances, collect or misuse Platform data, such as user names, addresses, phone numbers, or other sensitive information. Copying copyrighted text or using such content for mirrored, competitive, or unauthorized third-party sites is also prohibited.
<br />5. Infrastructure Disruption:
<br />Actions that overburden or disrupt the Platform’s infrastructure are not allowed. Examples include:
<br />Sending an unreasonable number of requests to Platform servers.
<br />Using scripts or tools that affect the Platform’s performance.
<br />Attempting to bypass measures put in place to limit or restrict Platform access.
<br />6. Harvesting and Unauthorized Communication:
<br />Collecting personally identifiable information or using communication systems provided by the Platform for commercial solicitation or unauthorized purposes is strictly prohibited.
    </p>
    <p className="mb-4">Special Provisions for Search Engines:
      <br />
      Operators of public search engines may use tools such as spiders to copy Platform materials solely for creating publicly available search indices. However, they are not allowed to store, cache, or archive such materials. Exceptions to these provisions may be revoked at any time at the discretion of Beiyo Technven Private Limited.
    </p>
    <h1 className="font-bold">D. Use of Submitted Content</h1>
    <p className="mb-4">You hereby grant consent to Beiyo Technven Private Limited to collect, store, use, or dispose of any sensitive personal information requested or submitted by you at your sole discretion through our platform. Such information will be collected for the intended usage as per the terms and conditions agreed upon herein. Beiyo Technven Private Limited shall not be responsible for the authenticity of such personal information or sensitive personal data submitted by you.</p>
    <h2 className="font-bold">1. Consent for Use of Sensitive Personal Information</h2>
    <p className="mb-4">The Platform may now or in the future permit the submission of videos or other communications submitted by you and other users, including without limitation, your Profile, any Feedback, and all Submitted Content, and the hosting, sharing, and/or publishing of such Submitted Content. You understand that whether or not such Submitted Content is published, Beiyo Technven Private Limited does not guarantee any confidentiality with respect to any Submitted Content</p>
    <p className="mb-4">You agree that any Submitted Content provided by you for which you authorize to be searchable by Registered Users who have access to the Platform is provided on a non-proprietary and non-confidential basis. You agree that Beiyo Technven Private Limited shall be free to use or disseminate such freely searchable Submitted Content on an unrestricted basis for the purpose of providing the Services.</p>
    <p className="mb-4">Beiyo Technven Private Limited may also disclose user information including personal information if Beiyo Technven Private Limited reasonably believes that disclosure (i) is necessary in order to comply with a legal process (such as a court order, search warrant, etc.) or other legal requirement of any governmental authority, (ii) would potentially mitigate Beiyo Technven Private Limited’s liability in an actual or potential lawsuit, (iii) is otherwise necessary or appropriate to protect our rights or property, or the rights or property of any person or entity, (iv) to enforce this Agreement (including, but not limited to ensuring payment of fees by users), or (v) as may be required or necessary to deter illegal behaviour (including, but not limited to, fraud).</p>
    <h2 className="font-bold">2. Confidentiality</h2>
    <p className="mb-4">By registering on this website or by submitting your details, you disclaim your National Do Not Call Registry (NDNC) and authorize Beiyo Technven Private Limited and its representatives, partners, or third parties to contact you through call, SMS, E-Mail, WhatsApp, or through any other mode of communication for commercial/transactional/promotional or any other purposes. If you wish not to be contacted through the foregoing modes for the said purposes, you shall not submit your details herein.</p>
    <h2 className="font-bold">3. Consent for Communication</h2>
    <p className="mb-4">By registering on this website or by submitting your details, you disclaim your National Do Not Call Registry (NDNC) and authorize Beiyo Technven Private Limited and its representatives, partners, or third parties to contact you through call, SMS, E-Mail, WhatsApp, or through any other mode of communication for commercial/transactional/promotional or any other purposes. If you wish not to be contacted through the foregoing modes for the said purposes, you shall not submit your details herein.</p>
    <h2 className="font-bold">4. Your Representations and Warranties</h2>
    <p className="mb-4">You shall be solely responsible for your own Submitted Content and the consequences of posting or publishing it. In connection with Submitted Content, you affirm, represent, and/or warrant that: (a) you own or have the necessary licenses, rights, consents, to use and authorize Beiyo Technven Private Limited to use all patent, trademark, trade secret, copyright, or other proprietary rights in and to any and all Submitted Content to enable inclusion and use of the Submitted Content in the manner contemplated by the Platform and these Terms of Use; and (b) you have the written consent, release, and/or permission of each and every identifiable individual person in the Submitted Content to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the Submitted Content in the manner contemplated by the Platform and these Terms of Use. You agree to pay for all royalties, fees, and any other monies owing to any person by reason of any Submitted Content posted by you to or through the Platform.</p>
    <h2 className="font-bold">5. Your Ownership Rights and License to Beiyo</h2>
    <p className="mb-4">You retain all of your ownership rights in your Submitted Content. However, by submitting the Submitted Content to Beiyo Technven Private Limited for posting on the Platform, you hereby grant, and you represent and warrant that you have the right to grant, to Beiyo Technven Private Limited a perpetual, worldwide, non-exclusive, royalty-free, sublicenseable, and transferable license to link to, use, reproduce, distribute, reformat, translate, prepare derivative works of, display, and perform the Submitted Content in connection with the Platform and Beiyo Technven Private Limited’s (and its successor’s) business operations, including without limitation, for the promotion and redistribution of any part or all of the Platform, and any derivative works thereof, in any media formats and through any media channels. You also hereby grant each user of the Platform a non-exclusive license to access your Submitted Content through the Platform, and to use, reproduce, distribute, prepare derivative works of, display and perform such Submitted Content as permitted through the functionality of the Platform and under these Terms of Use. The foregoing license granted by you terminates once you remove or delete the Submitted Content from the Platform.</p>
    <p className="mb-4">You acknowledge and understand that the technical processing and transmission of the Platform, including your Submitted Content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
    <p className="mb-4">You may remove your Submitted Content from the Platform at any time. If you choose to remove your Submitted Content, the license granted above will automatically expire.</p>
    <h2 className="font-bold">6. Beiyo's Disclaimers and Right to Remove</h2>
    <p className="mb-4">Beiyo Technven Private Limited does not endorse any Submitted Content, or any opinion, recommendation, or advice expressed therein, and Beiyo Technven Private Limited expressly disclaims any and all liability in connection with all Submitted Content. Beiyo Technven Private Limited does not permit copyright infringing activities and infringement of intellectual property rights on the Platform, and Beiyo Technven Private Limited will remove any Data (as defined below) or Submitted Content if properly notified, pursuant to the "take down" notification procedure described below, that such Posting or Submitted Content infringes on another's intellectual property rights. Beiyo Technven Private Limited reserves the right to remove any Data or Submitted Content without prior notice. Beiyo Technven Private Limited will also terminate a user's access to the Platform if he or she is determined to be a repeat infringer. A repeat infringer is a Platform user who has been notified of infringing activity more than twice and/or has had Submitted Content removed from the Platform more than twice. Beiyo Technven Private Limited also reserves the right, in its sole and absolute discretion, to decide whether any Data or Submitted Content is appropriate and complies with these Terms of Use for all violations, in addition to copyright infringement and violations of intellectual property law, including, but not limited to, pornography, obscene or defamatory material, or excessive length. Beiyo Technven Private Limited may remove such Submitted Content and/or terminate a user's access for uploading such material in violation of these Terms of Use at any time, without prior notice and in its sole discretion.</p>
    <p className="mb-4">You acknowledge and understand that when using the Platform, you will be exposed to Submitted Content from a variety of sources, and that Beiyo Technven Private Limited is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Submitted Content. You further acknowledge and understand that you may be exposed to Submitted Content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Beiyo Technven Private Limited with respect thereto, and agree to indemnify and hold Beiyo Technven Private Limited, its owners, members, managers, operators, directors, officers, agents, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the Platform.</p>
    <p className="mb-4">You are solely responsible for the photos, profiles, and other content, including, without limitation, Submitted Content that you publish or display on or through the Platform, or transmit to other Platform users. You understand and agree that Beiyo Technven Private Limited may, in its sole discretion and without incurring any liability, review and delete or remove any Submitted Content that violates this Agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of Platform users or others.</p>
    <h2 className="font-bold">7. Suggestions</h2>
    <p className="mb-4">If you send or transmit any communications, comments, questions, suggestions, or related materials to Beiyo Technven Private Limited, whether by letter, email, telephone, or otherwise (collectively, "Suggestions"), suggesting or recommending changes to the Platform, including, without limitation, new features or functionality relating thereto, all such Suggestions are, and will be treated as, non-confidential and non-proprietary. You hereby assign all right, title, and interest in, and Beiyo Technven Private Limited is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Suggestions, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Suggestions. You understand and agree that Beiyo Technven Private Limited is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Suggestions, and you have no right to compel such use, display, reproduction, or distribution or seek recognition if the Suggestions are in fact implemented.
    </p>
    <h1 className="font-bold">E. COPYRIGHT INFRINGEMENT TAKE DOWN PROCEDURE</h1>
    <p className="mb-4">Beiyo Technven Private Limited has high regard for intellectual property and expects the same level of standard to be employed by its users. Beiyo may, in appropriate circumstances and at its discretion, terminate the Account or prohibit access to the Platform of users who infringe upon the intellectual property rights of others.</p>
        <p className="mb-4">If you believe that your work has been copied and posted on the Platform in a way that constitutes copyright infringement and/or trademark infringement, please send the following information to us at support@beiyo.in:</p>
         <p className="mb-4">(i) Identification of the copyrighted and/or trademarked work claimed to have been infringed, or, if multiple works at a single online site are covered by a single notification, a representative list of such works at that site.</p>
         <p className="mb-4">(ii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled at the Platform, and information reasonably sufficient to permit Beiyo to locate the material.
         </p>
         <p className="mb-4">(iii) A written statement that you have a good faith belief that the disputed use is not authorized by the copyright and/or trademark owner, its agent, or the law.</p>
         <p className="mb-4">(iv) Information reasonably sufficient to permit Beiyo to contact you as the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted</p>
         <p className="mb-4">(v) An electronic or physical signature of the person authorized to act on behalf of the owner of an exclusive right.</p>
         <p className="mb-4">(vi) A statement by you, made under penalty of perjury, that the information in your report is accurate and that you are the owner of the exclusive right or authorized to act on behalf of the owner of the exclusive right. A statement by you comprised of the foregoing points is referred to herein as the "Notice."</p>
         <p className="mb-4">Only the intellectual property rights owner is permitted to report potentially infringing items through Beiyo’s reporting system set forth above. If you are not the intellectual property rights owner, you should contact the intellectual property rights owner, and they can choose whether to use the procedures set forth in these Terms of Use.</p>
         <hr />
         <h1 className="font-bold">F. MODIFICATIONS TO OR TERMINATION OF PLATFORM</h1>
         <h2 className="font-bold">1. Modification or Cessation of Platform</h2>
         <p className="mb-4">Beiyo reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Platform (or any part thereof) with or without notice and in its sole discretion. You agree that Beiyo shall not be liable to you or to any third party for any modification, suspension, or discontinuance of Beiyo services.</p>
         <h2 className="font-bold">2. Termination by Beiyo</h2>
         <p className="mb-4">You hereby acknowledge and agree that Beiyo, in its sole and absolute discretion, has the right (but not the obligation) to delete, terminate, or deactivate your Account, block your email or IP address, cancel the Platform or otherwise terminate your access to or participation in the use of the Platform (or any part thereof), or remove and discard any Submitted Content on the Platform ("Termination of Service"), immediately and without notice, for any reason, including without limitation, Account inactivity or if Beiyo believes or has reason to believe that you have violated any provision of the Terms of Use.</p>
         <h2 className="font-bold">3. Termination by You</h2>
         <p className="mb-4">Since your usage of the Platform is linked to the duration of your stay with Beiyo, your usage of the Platform shall be terminated when your stay with Beiyo is terminated and/or expires.</p>
         <h2 className="font-bold">4. Effect of Termination</h2>
         <p className="mb-4">Upon termination of your Account, your right to participate in the Platform shall automatically be terminated. In the event of Termination of Service, your Account will be disabled and you may not be granted access to your Account or any files or other data contained in your Account. Notwithstanding the foregoing, residual data may remain in the Beiyo Platform. Unless Beiyo has previously cancelled or terminated your use of the Platform (in which case subsequent notice by Beiyo shall not be required), if you provided a valid email address during registration, Beiyo will notify you via email of any such termination or cancellation, which shall be effective immediately upon Beiyo's delivery of such notice.</p>
         <p className="mb-4">Upon Termination of Service, the following shall occur: all licenses granted to you hereunder will immediately terminate; and you shall promptly destroy all copies of Beiyo Data (as defined below), Marks (as defined below), and other content in your possession or control. You further acknowledge and agree that Beiyo shall not be liable to you or any third party for any termination of your access to the Platform. Upon Termination of Service, Beiyo retains the right to use any data collected from your use of the Platform for internal analysis and archival purposes, and all related licenses you have granted Beiyo hereunder shall remain in effect for the foregoing purpose. In no event is Beiyo obligated to return any Submitted Content to you. Sections which are designed/required to survive termination shall survive expiration or termination of the Platform or your Account.</p>
         <p className="mb-4">You agree to indemnify and hold Beiyo, and its officers, managers, members, affiliates, successor, assigns, directors, agents, suppliers, and employees harmless from any claim or demand, including reasonable attorneys' fees and court costs, made by any third party due to or arising out of the Termination of Service.</p>
        <hr />
        <h1 className="font-bold">G. INTELLECTUAL PROPERTY RIGHTS</h1>
        <h2 className="font-bold">1. Beiyo owns or holds the Licenses to all Data and Marks on the Platform</h2>
        <p className="mb-4">The content on the Platform (exclusive of all Submitted Content), including without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like ("Data") and the trademarks, service marks and logos contained therein ("Marks"), are owned by Beiyo. Other trademarks, names, and logos on the Platform are the property of their respective owners.</p>
        <p className="mb-4">Data on the Platform is provided to you as is for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. Beiyo reserves all rights not expressly granted in and to the Platform and the Data. You agree not to use, copy, or distribute, any of the Data other than as expressly permitted herein, including any use, copying, or distribution of Submitted Content obtained through the Platform for any commercial purposes. If you download or print a copy of the Data for personal use, you must retain all copyright and other proprietary notices contained thereon. You agree not to circumvent, disable or otherwise interfere with security features of the Platform or features that prevent or restrict use or copying of any Data or enforce limitations on use of the Platform or the Data therein.</p>
        <h2 className="font-bold">2. Beiyo's License to You for the Use of Data and Marks</h2>
        <p className="mb-4">The Platform contains Beiyo's Data and Marks, which are, or may become, protected by copyright, trademark, patent, trade secret and other laws, and Beiyo owns and retains all rights in the Beiyo Data and Marks. Subject to these Terms of Use, Beiyo hereby grants you a limited, revocable, non-transferable, no sublicensable license to reproduce and display the Beiyo Data (excluding any software source code) solely for your personal use in connection with accessing and participating in the Platform. The Platform may also contain Data of other users or licensors, which you shall not copy, modify, translate, publish, broadcast, transmit, distribute, perform, display, or sell.</p>
          
          <h1 className="font-bold">H. DISPUTE RESOLUTION</h1>
          <p className="mb-4">If a dispute arises between you and BEIYO Technven Private Limited, our goal is to provide you with a neutral and cost-effective means of resolving the dispute quickly. Accordingly, you and BEIYO Technven Private Limited hereby agree to resolve any claim or controversy at law and equity that arises out of the Terms of Use or the Platform in accordance with this Section H or as we and you otherwise agree in writing. Before resorting to the filing of a formal lawsuit, we strongly encourage you to first contact us directly to seek a resolution via e-mail at ping@beiyo.com. The dispute shall be resolved through arbitration by a sole arbitrator appointed by BEIYO under the Arbitration and Conciliation Act, 1996, with the seat of arbitration being New Delhi. The language of arbitration shall be English.
          </p>
          <p className="mb-4">The Terms of Use shall be governed in all respects by the laws of India and any legal proceeding, subject to the above, arising out of this Agreement will occur exclusively in the courts located in New Delhi, India.</p>
         <h1 className="font-bold">I. ADVERTISEMENTS</h1>
         <p className="mb-4">Aspects of the Platform and other BEIYO services may be supported by advertising revenue. As such, BEIYO may display advertisements and promotions on the service. The manner, mode, and extent of advertising by BEIYO on the Platform are subject to change, and the appearance of advertisements on the Platform does not necessarily imply endorsement by BEIYO of any advertised products or services. You agree that BEIYO shall not be responsible or liable for any loss or damage of any sort incurred by you as a result of any such dealings or as the result of the presence of such advertisers on the Platform.</p>
         <h1 className="font-bold">J. THIRD-PARTY LINKS, CONTACT FORMS, AND PHONE NUMBERS</h1>
         <p className="mb-4">The Platform may provide, or third parties may provide, links, contact forms, and/or phone numbers to other Platforms or resources, including, without limitation, social networking, blogging, and similar Platforms through which you are able to log into the Platform using your existing account and log-in credentials for such third-party Platforms. Certain areas of the Platform may allow you to interact and/or conduct transactions with such third-party sites, and, if applicable, allow you to configure your privacy settings in your third-party site account to permit your activities on the Platform to be shared with your contacts in your third-party site account. Because BEIYO has no control over such sites and resources, you acknowledge and agree that BEIYO is not responsible for the availability of such external sites or resources, and is not responsible or liable for any content, advertising, products, goods, or services on or available from such Platforms or resources. Unless expressly stated on the Platform, links to third-party sites should in no way be considered as or interpreted to be BEIYO's endorsement of such third-party sites or any product or service offered through them.</p>
          <p className="mb-4">You further acknowledge and agree that BEIYO shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, advertising, product, goods, or services available on or through any such Platform or resource. The third-party Platform may have different privacy policies, terms and conditions, and business practices than BEIYO. In certain situations, you may be transferred to a third-party Platform through a link or connected to a third-party resource by a contact form or phone, but it may appear that you are still on this Platform or transacting with BEIYO. In these situations, you acknowledge and agree that the third-party Platform's terms and conditions and privacy policy apply in this situation. Your dealings and communications through the Platform with any party other than BEIYO are solely between you and such third party. Any complaints, concerns, or questions you have relating to materials provided by third parties should be forwarded directly to the applicable third party.</p>
          <h1 className="font-bold">K. DISCLAIMER OF WARRANTIES</h1>
          <p className="mb-4">YOU AGREE THAT YOUR USE OF THE PLATFORM SHALL BE AT YOUR OWN RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, BEIYO AND ITS OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, SUCCESSORS, ASSIGNS, SUBSIDIARIES, AFFILIATES, SUPPLIERS, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, AND MAKE NO WARRANTIES, REPRESENTATIONS, OR GUARANTEES IN CONNECTION WITH THIS PLATFORM, THE SERVICES OFFERED ON OR THROUGH THIS PLATFORM, ANY DATA, MATERIALS, SUBMITTED CONTENT, RELATING TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY, OR COMPLETENESS OF ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THIS PLATFORM, INCLUDING WITHOUT LIMITATION THE MATERIALS, DATA AND SUBMITTED CONTENT OF OTHER USERS OF THIS SITE OR OTHER THIRD PARTIES. UNLESS OTHERWISE EXPLICITLY STATED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS PLATFORM, THE SERVICES OFFERED ON OR THROUGH THIS PLATFORM, DATA, MATERIALS, SUBMITTED CONTENT, AND ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THIS PLATFORM IS PROVIDED TO YOU ON AN "AS IS," "AS AVAILABLE," AND "WHERE IS" BASIS WITH NO WARRANTY OR IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS. BEIYO DOES NOT PROVIDE ANY WARRANTIES AGAINST ERRORS, MISTAKES, OR INACCURACIES OF DATA, CONTENT, INFORMATION, MATERIALS, SUBSTANCE OF THE PLATFORM OR SUBMITTED CONTENT, ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE PLATFORM BY ANY THIRD PARTY, ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE PLATFORM, ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY OR SERVICE USER OR SERVICE PROVIDER, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY DATA, CONTENT, INFORMATION, MATERIALS, SUBSTANCE OF THE PLATFORM OR SUBMITTED CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE PLATFORM. BEIYO DOES NOT ENDORSE, WARRANT, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE PLATFORM OR ANY HYPERLINKED SITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISEMENT.</p>
          <p className="mb-4">CERTAIN SERVICES ON THE PLATFORM OR ON THE PREMISES MAY BE PROVIDED THROUGH A THIRD PARTY VENDOR, IT IS AGREED AND CLARIFIED THAT UNDER NO CIRCUMSTANCES SHALL BEIYO BE LIABLE FOR THE PROVISION OF ANY SUCH SERVICES AND YOU SHALL HAVE RIGHTS DIRECTLY AGAINST SUCH VENDOR FOR ANY DEFICIENCY OR LOSS ARISING FROM THE RESPECTIVE SERVICES, AND BEIYO SHALL IN NO EVENT BE LIABLE FOR ANY CONSEQUENCES ARISING THEREFROM. BEIYO IS MERELY ACTING AS A FACILITATOR OF SUCH THIRD-PARTY SERVICES FOR YOU AND IS NOT LIABLE FOR ANY CONSEQUENCES ARISING THEREFROM.</p>
          <h1 className="font-bold">L. LIMITATIONS OF LIABILITY</h1>
          <p className="mb-4">IN NO EVENT SHALL BEIYO, OR ITS RESPECTIVE OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, SUCCESSORS, ASSIGNS, SUBSIDIARIES, AFFILIATES, SUPPLIERS, ATTORNEYS, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, CONSEQUENTIAL, OR EXEMPLARY DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF BUSINESS, REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE) WHATSOEVER RESULTING FROM (I) ANY ERRORS, MISTAKES, OR INACCURACIES OF DATA, MARKS, CONTENT, INFORMATION, MATERIALS, OR SUBSTANCE OF THE PLATFORM OR SUBMITTED CONTENT; (II) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN; (III) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE PLATFORM; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE PLATFORM; (V) ANY ERRORS OR OMISSIONS IN ANY DATA, CONTENT, INFORMATION, MATERIALS OR SUBSTANCE OF THE PLATFORM OR SUBMITTED CONTENT; (VI) ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY; OR (VII) ANY USE OF ANY DATA, MARKS, CONTENT, INFORMATION, MATERIALS, OR SUBSTANCE OF THE PLATFORM OR SUBMITTED CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE ON OR THROUGH THE PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT BEIYO IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
          <p className="mb-4">IN NO EVENT SHALL THE TOTAL, AGGREGATE LIABILITY OF BEIYO, OR ANY OF THE ABOVE-REFERENCED RESPECTIVE PARTIES, ARISING FROM OR RELATING TO THE PLATFORM, AND/OR SUBMITTED CONTENT EXCEED THE SIX-MONTH FEES ACTUALLY PAID TO BEIYO BY YOU.</p>
          <p className="mb-4">FORCE MAJEURE: NEITHER BEIYO NOR YOU SHALL BE LIABLE TO THE OTHER FOR ANY DELAY OR FAILURE IN PERFORMANCE UNDER THE TERMS OF USE, OTHER THAN PAYMENT OBLIGATIONS, ARISING OUT OF A CAUSE BEYOND ITS CONTROL AND WITHOUT ITS FAULT OR NEGLIGENCE. SUCH CAUSES MAY INCLUDE, BUT ARE NOT LIMITED TO FIRES, FLOODS, EARTHQUAKES, STRIKES, UNAVAILABILITY OF NECESSARY UTILITIES, BLACKOUTS, ACTS OF GOD, ACTS OF DECLARED OR UNDECLARED WAR, ACTS OF REGULATORY AGENCIES, OR NATIONAL DISASTERS.
          </p>
          <h1 className="font-bold">M. INDEMNIFICATION AND RELEASE</h1>
          <p className="mb-4">You agree to defend, indemnify and hold harmless BEIYO, and its officers, managers, members, directors, employees, successors, assigns, subsidiaries, affiliates, suppliers, and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorneys' fees) arising from your use of, access to, and participation in the platform; your violation of any provision of the Terms of Use, including the Privacy Policy; your violation of any third-party right, including without limitation any copyright, property, proprietary, intellectual property, or privacy right; or any claim that your submitted content caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the platform.</p>
          <p className="mb-4">The Terms of Use, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by BEIYO without restriction.</p>
          <h1 className="font-bold">N. NO THIRD-PARTY BENEFICIARIES</h1>
          <p className="mb-4">You agree that, except as otherwise expressly provided in the Terms of Use, there shall be no third-party beneficiaries to the Terms of Use.</p>
         <h1 className="font-bold">O. Notice</h1>
         <p className="mb-4">You agree that BEIYO may provide you with notices, including those regarding changes to the Terms of Use, by email, regular mail, or postings on the platform.</p>
         <h1 className="font-bold">P. GENERAL INFORMATION</h1>
         <h2 className="font-bold">1. Entire Terms of Use</h2>
         <p className="mb-4">The Terms of Use, together with the Privacy Policy and any other legal notices or Additional Policies published by BEIYO on the platform, shall constitute the entire agreement between you and BEIYO concerning the platform. If any provision of the Terms of Use is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of the Terms of Use, which shall remain in full force and effect.</p>
         <p className="mb-4">No waiver of any provision of these Terms of Use shall be deemed a further or continuing waiver of such term or any other term, and BEIYO's failure to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
         <h2 className="font-bold">2. Section Headings</h2>
         <p className="mb-4">The section headings in the Terms of Use are for convenience only and have no legal or contractual effect.</p>
         <h1 className="font-bold">Q. OFFERS AND DISCOUNTS</h1>
         <p className="mb-4">
        1. BEIYO provides attractive offers and discounts for new/first-time users. You may avail these discounts by using the 'Reserve Now' option on our website.
<br /> 2. By selecting the 'Reserve Now' option, you may unlock assured discounts on payment of a refundable and nominal 'Fee' and schedule a visit to our property. Upon your successful onboarding, you may avail the unlocked discount only on the rent payable by you for the first month of your stay.
<br /> 3. In case you don't wish to onboard after visiting our property, you may claim the refund of the 'Fee'.
<br /> 4. The discount offered to you will be inclusive of the 'Fee' i.e. the initial fee/payment cannot be claimed separately or over and above the total discount offered to you.
<br /> 5. The 'Reserve Now' option shall only be applicable if the 'Fee' is received by BEIYO, at a minimum of 12 (twelve) hours prior to the payment of the final booking amount.
         </p>
         <h1 className="font-bold">R. REFERRAL COUNT AND PAYOUT TERMS </h1>
         <p className="mb-4">
        1. No TDS will be deducted for payouts for the first Rs. 10,000.
<br /> 2. Post Rs. 10,000 cumulative payouts, you can opt to either continue receiving money in your account/wallet with 20% TDS deductions or update your PAN card details.
<br /> 3. Post the verification of PAN card, 3.75% TDS will be deducted for every successive payout.
<br /> 4. Please note that the first payout beyond Rs. 10,000 will account for TDS cut for first Rs. 10,000 as well.
<br /> 5. All or any payouts will be done as per the levels mentioned in the application at the time referral leads are submitted.
<br /> 6. Those referral leads already available with BEIYO’s database shall not be eligible for any referral payouts.
<br /> 7. All referral payouts shall be subject to BEIYO's ethical guidelines and any suspicious activity shall be flagged. BEIYO also retains the right to initiate appropriate action against any such activity and/or person.
<br /> 8. BEIYO reserves the right to change the Terms and Conditions and/or the payout policy at its own discretion.
<br /> 9. The approval or decline of referral payouts shall be subject to the final decision of BEIYO at all times.
         </p>
         <h1 className="font-bold">S. REMOTE BOOKING TERMS</h1>
         <p className="mb-4">In case you are unable to visit a BEIYO property immediately, then you can opt for a remote booking option. However, this remote booking option is currently available only in select BEIYO properties.</p>
         <p className="mb-4">Below are the steps for remote booking:</p>
         <p className="mb-4">Step 1: You share your details on the website.
<br />Step 2: A dedicated sales expert will reach out and help you select the ideal property for you.
<br />Step 3: You'll confirm the booking and receive a link to download the BEIYO - Resident App to pay the token amount.
<br />Step 4: Once the token amount is paid, you visit the property at a convenient time and our team member will show you all the rooms available as per your finalized category.
<br />Step 5: Select a room in the same budget or you can choose to upgrade as well (subject to availability).
<br />Step 6: Make payment of the balance amount.
</p>
<h1 className="font-bold">T. DISCLAIMER FOR FAKE CALLS AND OTHER SIMILAR PHISHING, SPAMMING OR FRAUDULENT ACTIVITIES</h1>
<p className="mb-4">Please beware of fraudulent activities by unauthorized individuals or entities claiming to be associated with BEIYO and/or its founders. These fraudsters attempt to deceive potential customers by using our company's name and reputation for their unlawful gains. You are requested to verify the authenticity before initiating any payment. Please be informed that BEIYO does not engage in any unsolicited communication, such as phone calls, emails, or messages, asking for sensitive personal information, account details, or any payment-related transactions. In no event shall BEIYO be liable for any direct or indirect damages arising from reliance on the information provided in this warning. We disclaim any liability for losses or damages incurred due to fraudulent actions committed by third parties misrepresenting themselves as BEIYO.</p>
<h1 className="font-bold">Please note:</h1>
<p className="mb-4">The room selection happens on a first-come-first-served basis and is subject to availability. We recommend you to come as soon as possible in order to have more options of rooms to select from.</p>
<p>© 2024 BEIYO. All Rights Reserved.</p>
        </div>
        <br />

      </div>
    </div>
  );
};

export default TermsandConditon;
